### ISSUE TITLE
Template support for Visual Studio 2019

### ISSUE THREAD

**Issue by CoolBots** [BlizzCrafter/MonoGame.Forms#22]
Currently the MonoGame.Forms template (linked from Readme: https://marketplace.visualstudio.com/items?itemName=SandboxBlizz.MonoGameForms42) only supports VS 2017. Please update the template to support VS 2019. Thank you!

**Comment by monogamefan** [comment]
Is it possible to update to VS2022 too?

**Comment by BlizzCrafter** [comment]
Added template support for Visual Studio 2019 and 2022.

https://marketplace.visualstudio.com/items?itemName=BlizzCrafter.MonoGameForms1337
