### ISSUE TITLE
Requesting to update .Net5 Form Support

### ISSUE THREAD

**Issue by maniX101** [BlizzCrafter/MonoGame.Forms#33]
Hello,

Can you add .Net5-Windows Form Support ?

**Comment by maniX101** [comment]
I managed to port DX WinForms to .Net5 WinForms, need help with GL WinForms port help?

SDL is removed from `MonoGame.Framework.dll` and how to implement the SDL2 ?

**Comment by MasterSkriptor** [comment]
Any update on this being merged? I would love to use it in dotnet 5

**Comment by Blue-Footed-Booby** [comment]
Is there a vague ETA for this? "No" is a valid answer; I get that life happens, and the world is kinda crazy right now.

**Comment by BlizzCrafter** [comment]
See #38
