### ISSUE TITLE
Error while building project that uses MonoGame.Forms, on Linux

### ISSUE THREAD

**Issue by randrade23** [BlizzCrafter/MonoGame.Forms#34]
Hello,

I have a project that has MonoGame.Forms.DX as a dependency through NuGet, and it builds correctly under Windows, but fails to build under Linux.

When building this project under Linux (using ```msbuild```, and after running ```nuget restore``` on the solution), it throws an error saying it could not find the "build" folder inside the MonoGame.Forms.DX package folder - presumably because this folder is named "Build" rather than "build", and ext4 is a case sensitive file system.

```
#13 2.249 /app/[redacted]/[redacted].csproj(553,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ../packages/MonoGame.Forms.DX.2.4.0/build/MonoGame.Forms.DX.targets.
#13 2.259 Done Building Project "/app/[redacted]/[redacted].csproj" (Rebuild target(s)) -- FAILED.
```

Renaming the folder from "Build" to "build" after restoring the packages works around this problem, and allows my project to build correctly.

**Comment by sqrMin1** [comment]
Thanks for sharing the solution! I will take a look into it when I have time.

**Comment by BlizzCrafter** [comment]
The nuspec file was updated according to your information, but unfortunately the GL project is not supported anymore.

If you want to create your own editor or tool on linux you should try [this Gtk solution](https://www.nuget.org/packages/MonoGame.Template.Gtk.CSharp/) instead (it's not mine).
