### ISSUE TITLE
Monogame.Forms not rendering blue screen after building solution

### ISSUE THREAD

**Issue by RamiMorrar** [BlizzCrafter/MonoGame.Forms#36]
For some reason, the screen just doesn't draw out after running the solution on my end. The toolbox draw test is showing but not the actual game screen itself,

**Comment by PartumGames** [comment]
I can't even inherit from the GameControl class like it shows in the readme. I import the nuget package and it's like VS doesn't even recognize it's there.

**Comment by PartumGames** [comment]
I can't even inherit from the GameControl class like it shows in the readme. I import the nuget package and it's like VS doesn't even recognize it's there.

**Comment by RamiMorrar** [comment]
Did you try downloading the package itself and adding all the dlls in the right places? For some reason I'm missing a bunch of dlls

**Comment by PartumGames** [comment]
I eventually got it to work, with nuget.  It seems to work with .Net Framework 4.7.2,  but not .netcore 3.1 or .netcore 5.0. Which is an issue because my Engine uses .netcore, and when I import my engine into the project. It throws errors.

**Comment by RamiMorrar** [comment]
Was missing a dll file. Got it working now. W00t.


Also yeah it only targets .NET 4.X. doesn"t work for anything lower.

**Comment by PartumGames** [comment]
Which dll?

**Comment by RamiMorrar** [comment]
SharpDX.XAudio2
