### ISSUE TITLE
supported .net frameworks

### ISSUE THREAD

**Issue by ghost** [BlizzCrafter/MonoGame.Forms#38]
Hi

What frameworkz czn I target from this list?
4.x?
5.0?
6.0?

.net core ?

**Comment by kaltinril** [comment]
Only on .net Framework, not .net core.  I just learned this myself.

It means I can't link my other projects in to use them as references.

**Comment by monogamefan** [comment]
What is the reason .net core can't be used?

Is it correct .NET 6.0 can be used too since this is a bit the continuation of .net core (cross platform)?

**Comment by BlizzCrafter** [comment]
The minimum version you need is .NET Framework 4.5.1, but it's possible to use higher versions.

.NET 5 and above is currently not officially supported, but I heared that one community member here had success porting it to .NET 5 already.

I may take a look into it if I have more time.

**Comment by hellphreak** [comment]
I think you should try to support .NET 6.0 too because microsoft is stopping support for .net 5 soon.

**Comment by cyf-gh** [comment]
MonoGame.Forms.DX is easy to migrate to .Net Core 3.1. I successfully made one running as well. But I have not tested MonoGame.Forms.Tests.DX yet.
![20220501-193559127](https://user-images.githubusercontent.com/11147632/166144085-840cdfce-d0ad-465f-a854-b239684c682c.png)

![20220501-193811704](https://user-images.githubusercontent.com/11147632/166144172-a1139a29-0c70-48ab-9143-ade1ae62d923.png)

Here's my way to migrate MonoGame.Forms.DX to .Net Core 3.1 / 5 in haste.

1. Create a new .Net Core 3.1 / 5 C# Library Project.
2. Drag all source code and content files from [MonoGame.Forms.DX](https://github.com/BlizzCrafter/MonoGame.Forms/tree/master/MonoGame.Forms.DX) to the new project.
3. Right click on the Resources.resx file and click Property. Set [Custom Tool] to ResXFileCodeGenerator.
4. Build the project and now it's a .Net Core 3.1 / 5 MonoGame.Forms.DX !

If the auto generated AssemblyInfo.cs file cause an error, just delete all System.Reflection.AssemblyXXXXXAttribute code in this file and it should work.

**Comment by BlizzCrafter** [comment]
I recently created a .Net 6 version of MonoGame.Forms on a seperated branch for everyone to try out.

Here it is: https://github.com/BlizzCrafter/MonoGame.Forms/tree/Net6.0
