### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by EzeKees** [BlizzCrafter/MonoGame.Forms#40]
Hi, first thanks for this, it's just what I needed and it's well documented.
The only thing I need to know is if you can set a maximum frame rate (limit it).
Is this project always in sync with VSync?
Thank you

**Comment by BlizzCrafter** [comment]
This implementation is locked to 60 fps, because of Windows Forms limitations.

I'm happy to hear that you like this project and that it's helpful.

Cheers
