### ISSUE TITLE
[Net6] Nuget Package not usable in Net6 projects

### ISSUE THREAD

**Issue by BlizzCrafter** [BlizzCrafter/MonoGame.Forms#44]
It's somehow not possible to generate a working nuget package for Net6 projects.

I tried to generate one with this new .nuspec file:
https://github.com/BlizzCrafter/MonoGame.Forms/blob/Net6.0/MonoGame.Forms/MonoGame.Forms.nuspec

When trying to install the generated nuget package on a new Net6 project I get this error message:

> error NU1202	Package MonoGame.Forms.DX 6.0.0 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0) 
> Package  MonoGame.Forms.DX 6.0.0 does not support any target frameworks.

Which is surprising, because the target framework was clearly set in the .nuspec file.

If someone knows whats going on, then please drop a line here.

**Comment by AristurtleDev** [comment]
Hey @BlizzCrafter how/what are you using to generate your NuGet package?

I was just able to generate one from your Net6.0 branch using just the basic `dotnet pack` command.  Here is the generated NuGet Info

![image](https://github.com/BlizzCrafter/MonoGame.Forms/assets/103014489/a6d92233-f779-418a-a4b3-fb5758808070)

**Comment by BlizzCrafter** [comment]
Hey @AristurtleDev and thx for trying to help.

Please create a new WindowsForms (Net6) project now and try to install your generated package. Because this is what fails for me with the above mentioned error message.

I generated the package with dotnet pack and nuget pack. Generation works, but installing does not work.

Would be nice if you could try this.

**Comment by AristurtleDev** [comment]
Hey @BlizzCrafter 

So I was able to get it working no issues?  Here are the steps I did

1. From the `Net6.0` branch of your code, I did a `dotnet pack` on the main project.
2. Created a new folder on my desktop called `mgforms`
3. Created a new folder inside this called `NuGet` and put the `MonoGame.Forms.DX.6.0.0.0.nupkg` inside this folder
4. Created a new Windows Form Application called `MonoGamesFormTest` and put it inside the `mgforms` directory I initially created
5. Edited my NuGet config inside Visual Studio to include the new local path to the `mgforms/NuGet` directory i mentioned in step 3.
6. Added the `MonoGame.Forms.DX version 6.0.0.0` nuget

I then created a sample application as outlined in your README (only I didn't tell the control to fill lol)

This is a busy screenshot but I tried to include all relavent information in one pic. You can see the `.csproj` showing the NuGet package reference. Beside that is the NuGet Pacakage Manager window showing the package.  The bottom right corner shows where I configured my Locals packages and you can see in the NuGet Pacakage Manager window that I have it set to Locals. You can also see in the Solution Explorer that the package is added under dependencies.  And finally in the bottom right you can see the Windows Form application running with the cornflour blue window.

![image](https://github.com/BlizzCrafter/MonoGame.Forms/assets/103014489/dcacd8f0-5995-4f59-b48b-ee473cef142a)

**Comment by BlizzCrafter** [comment]
Thank you very much for your detailed step by step instructions, much appreciated.

Also very nice to see that the generated package (based on the nuspec file) works fine.

However, it still doesnt work on my end. Maybe there is something wrong with my machine, I don't know. I made sure to update Visual Studio to the newest version, but still no success.

When I am back from vaccation I will try it with other machines. Hopefully with more succes.

At least I know now that the nuspec file itself is correctly configured for Net6.

Thanks again for your effort!

**Comment by AristurtleDev** [comment]
No problem. If you need me to test any of it again or something, not sure if you're in the MonoGame discord, but if you are you can ping me or dm me there. I'm under the same name as here in the discord.

**Comment by BlizzCrafter** [comment]
I tried it again on other build machines and got it working.

I'm still not sure why it didn't work on other one. It was a fresh windows 10 machine with also fresh installations of nuget and Visual Studio.

However, the problem is solved now. 

Thanks again @AristurtleDev for testing!
