### ISSUE TITLE
possible memory leak while resizing ?

### ISSUE THREAD

**Issue by ZartoxGD** [BlizzCrafter/MonoGame.Forms#47]
Hi,

I wanted to post my problem on the MonoGame forum, but I can't create an account, and I'm not sure if I can ask here...

I have an issue that I can't seem to fix. I'm working on a project using MonoGame.Forms, which seems perfect for my needs, but when I resize the window containing my control, the memory usage keeps increasing and never goes back down. I tried using the sample project in this repository, but the same thing happens. Is this a common bug, or am I missing something obvious?

Here is a video showing the problem: https://imgur.com/a/px9mWRY

Thanks, have a nice day.

**Comment by ZartoxGD** [comment]
I found something, when i change the Docktype of the control to None the problem seems to be fixed, but how can I make the control take the whole space if i don't put the dock as Fill ? I think my problem is not from your code but from my ignorance... 

https://imgur.com/a/7KjIMa0

**Comment by BlizzCrafter** [comment]
Ididn't look into it so far, but this is probably caused by frequent render target recreations.

I would need to fix this inside the library.
